version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    cap_add:
      - SYS_NICE
  blog_rails:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog_rails
      - blog_bundle_path:/bundle/vendor
      - blog_node_modules:/blog_rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - BUNDLE_PATH=/bundle/vendor
  redis:
    image: redis:6.2.3

volumes:
  blog_bundle_path:
  mysql-db:
  blog_node_modules:
